import type { VehicleFormValues, VehicleStatus } from "@/types/vehicle";

export const vehicleStatusLabels: Record<VehicleStatus,string> = { AVAILABLE:"Available",IN_USE:"In Use",RESERVED:"Reserved",INSPECTION_REQUIRED:"Inspection Required",SERVICE_DUE:"Service Due",IN_SERVICE:"In Service",ACCIDENT_REPAIR:"Accident Repair",NOT_ROADWORTHY:"Not Roadworthy",INACTIVE:"Inactive",SOLD:"Sold",DISPOSED:"Disposed",TRANSFERRED:"Transferred" };
export function normalizeSearch(value:string) { return value.toLowerCase().replace(/[^a-z0-9]/g,""); }
export function getExpiryStatus(expiry?: string|Date|null) { if(!expiry) return "MISSING" as const; const days=Math.ceil((new Date(expiry).getTime()-Date.now())/86400000); if(days<0)return "EXPIRED" as const;if(days<15)return "URGENT" as const;if(days<=30)return "ATTENTION" as const;if(days<=60)return "UPCOMING" as const;return "VALID" as const; }
export function canStartTrip(status:VehicleStatus) { return !["NOT_ROADWORTHY","ACCIDENT_REPAIR","INSPECTION_REQUIRED","INACTIVE","SOLD","DISPOSED","TRANSFERRED"].includes(status); }
export function getServiceStatus(currentKm:number,nextServiceKm?:number|null,nextServiceDate?:Date|null) { if(nextServiceKm!=null){const remaining=nextServiceKm-currentKm;if(remaining<0)return "OVERDUE" as const;if(remaining<=1000)return "DUE_SOON" as const;}if(nextServiceDate){const days=Math.ceil((nextServiceDate.getTime()-Date.now())/86400000);if(days<0)return "OVERDUE" as const;if(days<=30)return "DUE_SOON" as const;}return "UP_TO_DATE" as const; }
export function getDocumentSummary(expiryDates:(Date|null)[]) { if(!expiryDates.length)return "ATTENTION" as const;const statuses=expiryDates.map(getExpiryStatus);if(statuses.includes("EXPIRED"))return "EXPIRED" as const;if(statuses.includes("URGENT"))return "URGENT" as const;if(statuses.includes("ATTENTION")||statuses.includes("UPCOMING")||statuses.includes("MISSING"))return "ATTENTION" as const;return "VALID" as const; }
export function validateVehicle(values:VehicleFormValues, previousKm=0) { const errors:Record<string,string>={}; if(!values.vehicleCode?.trim())errors.vehicleCode="Vehicle ID is required.";if(!values.vehicleName?.trim())errors.vehicleName="Vehicle name is required.";if(!values.registrationNumber?.trim())errors.registrationNumber="Registration number is required.";if(!values.vehicleType)errors.vehicleType="Vehicle type is required.";if(!values.brand?.trim())errors.brand="Brand is required.";if(!values.model?.trim())errors.model="Model is required.";if(!values.fuelType)errors.fuelType="Fuel type is required.";if(!Number.isFinite(values.currentKm)||values.currentKm<0)errors.currentKm="Current KM must be a non-negative number.";else if(values.currentKm<previousKm)errors.currentKm="Current kilometre reading cannot be lower than the previous recorded reading.";const year=new Date().getFullYear();if(values.manufacturingYear&&(values.manufacturingYear<1900||values.manufacturingYear>year+1))errors.manufacturingYear="Enter a reasonable manufacturing year.";if(values.lastServiceKm!=null&&values.nextServiceKm!=null&&values.nextServiceKm<values.lastServiceKm)errors.nextServiceKm="Next service KM cannot be lower than last service KM.";return errors; }
