import Link from "next/link";
import { Wrench } from "lucide-react";
import { authenticatedUser } from "@/lib/access-control";
import { db } from "@/lib/db";
import { Card } from "@/components/ui/card";

export const dynamic = "force-dynamic";
const date = (value: Date | null) => value?.toLocaleDateString("en-GB") ?? "—";
export default async function ServiceSchedulePage() {
  const user = await authenticatedUser();
  const vehicles = await db.vehicle.findMany({ where: { companyId: user.companyId!, status: { notIn: ["SOLD", "DISPOSED"] } }, select: { id: true, vehicleName: true, registrationNumber: true, primaryPhotoUrl: true, currentKm: true, lastServiceDate: true, lastServiceKm: true, nextServiceDate: true, nextServiceKm: true, serviceInterval: true }, orderBy: { nextServiceDate: "asc" } });
  const now = new Date();
  return <div className="mx-auto max-w-[1400px]"><div className="flex items-end justify-between"><div><p className="text-xs font-medium text-slate-500">Maintenance Management</p><h1 className="mt-1 text-2xl font-bold">Service schedule</h1><p className="mt-1 text-sm text-slate-500">Monitor upcoming, due, and overdue vehicle maintenance.</p></div><Link href="/dashboard/maintenance/history" className="rounded-lg border px-4 py-2 text-xs font-semibold">Service history</Link></div><div className="mt-6 grid gap-5 md:grid-cols-2">{vehicles.map(vehicle => { const dateDue = vehicle.nextServiceDate && vehicle.nextServiceDate < now; const kmDue = vehicle.nextServiceKm != null && vehicle.currentKm >= vehicle.nextServiceKm; const overdue = dateDue || kmDue; return <Card key={vehicle.id} className="overflow-hidden"><div className="flex gap-4 p-5">{vehicle.primaryPhotoUrl ? <img src={vehicle.primaryPhotoUrl} alt="" className="size-16 rounded-lg object-cover"/> : <span className="grid size-16 place-items-center rounded-lg bg-blue-50 text-blue-600"><Wrench size={22}/></span>}<div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><div><h2 className="font-semibold">{vehicle.vehicleName}</h2><p className="mt-1 text-xs text-slate-500">{vehicle.registrationNumber} · {vehicle.currentKm.toLocaleString()} KM</p></div><span className={`h-fit rounded-full px-2 py-1 text-[10px] font-semibold ${overdue ? "bg-red-50 text-red-700" : "bg-emerald-50 text-emerald-700"}`}>{overdue ? "OVERDUE" : "UP TO DATE"}</span></div><div className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><p className="text-slate-400">Last service</p><p className="mt-1 font-medium">{date(vehicle.lastServiceDate)} · {vehicle.lastServiceKm?.toLocaleString() ?? "—"} KM</p></div><div><p className="text-slate-400">Next service</p><p className="mt-1 font-medium">{date(vehicle.nextServiceDate)} · {vehicle.nextServiceKm?.toLocaleString() ?? "—"} KM</p></div></div><Link href={`/vehicles/${vehicle.id}?tab=Maintenance`} className="mt-4 inline-block text-xs font-semibold text-blue-600">Add service / view details →</Link></div></div></Card>})}</div>{!vehicles.length && <Card className="mt-6 p-10 text-center text-sm text-slate-500">No vehicles found.</Card>}</div>;
}
