"use client";
import Link from "next/link";
import { FormEvent, useMemo, useState } from "react";
import { Plus, Search, X } from "lucide-react";
import { LICENCE_TYPES, licenceStatus, licenceStatusClass, type LicenceStatus } from "@/lib/licence";

type Driver = { id:string; name:string; employeeId:string|null; phone:string; status:string };
type Licence = { id:string; driverId:string; licenceNumber:string; licenceType:string; vehicleClass:string; issueDate:string; expiryDate:string; renewalStatus:string; operationalStatus:string; isCurrent:boolean; driver:{name:string;employeeId:string|null}; documents:{id:string;fileName:string;fileSize:number}[] };
const input = "mt-1 h-10 w-full rounded-lg border border-slate-200 px-3 text-sm outline-none focus:border-blue-500";
const label = "text-xs font-semibold text-slate-700";
const pretty = (s:string) => s.replaceAll("_", " ").replace(/\b\w/g, c=>c.toUpperCase());
const date = (s:string) => new Date(s).toLocaleDateString("en-GB");

export function LicenceManager({initialLicences,drivers}:{initialLicences:Licence[];drivers:Driver[]}) {
  const [licences,setLicences]=useState(initialLicences); const [open,setOpen]=useState(false); const [search,setSearch]=useState(""); const [status,setStatus]=useState("ALL"); const [type,setType]=useState("ALL"); const [expiry,setExpiry]=useState("ALL"); const [error,setError]=useState(""); const [saving,setSaving]=useState(false); const [today]=useState(()=>new Date());
  const rows=useMemo(()=>licences.filter(l=>{const s=licenceStatus(l,today); const q=search.toLowerCase(); const days=Math.ceil((new Date(l.expiryDate).getTime()-today.getTime())/86400000); return (!q||`${l.driver.name} ${l.driver.employeeId??""} ${l.licenceNumber}`.toLowerCase().includes(q))&&(status==="ALL"||s===status)&&(type==="ALL"||l.licenceType===type)&&(expiry==="ALL"||(expiry==="EXPIRED"?days<0:days>=0&&days<=Number(expiry)));}),[licences,search,status,type,expiry,today]);
  const current=licences.filter(l=>l.isCurrent); const counts=(s:LicenceStatus)=>current.filter(l=>licenceStatus(l,today)===s).length; const licensed=new Set(current.map(l=>l.driverId));
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError("");const form=new FormData(event.currentTarget);const body=Object.fromEntries(form.entries());const response=await fetch("/api/licences",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await response.json();if(!response.ok){setError(data.message);setSaving(false);return}const driver=drivers.find(d=>d.id===data.driverId)!;setLicences(v=>[{...data,issueDate:new Date(data.issueDate).toISOString(),expiryDate:new Date(data.expiryDate).toISOString(),driver:{name:driver.name,employeeId:driver.employeeId},documents:[]},...v.map(l=>l.driverId===data.driverId?{...l,isCurrent:false}:l)]);setOpen(false);setSaving(false);}
  const cards=[["Total licences",current.length],["Valid",counts("VALID")],["Expiring soon",counts("EXPIRING_SOON")],["Expired",counts("EXPIRED")],["Missing licence",drivers.filter(d=>!licensed.has(d.id)).length]];
  return <div className="mx-auto max-w-[1500px]"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-bold">Licence Management</h1><p className="mt-1 text-sm text-slate-500">Manage driver licences, validity, renewals and compliance.</p></div><button onClick={()=>setOpen(true)} className="inline-flex h-10 items-center gap-2 rounded-lg bg-blue-600 px-4 text-sm font-semibold text-white"><Plus size={16}/>Add Licence</button></div>
  <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{cards.map(([name,value])=><div key={name} className="rounded-xl border border-slate-200 bg-white p-5"><p className="text-xs text-slate-500">{name}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>)}</div>
  <div className="mt-6 rounded-xl border border-slate-200 bg-white"><div className="grid gap-3 border-b p-4 md:grid-cols-[1fr_180px_180px_180px]"><label className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} className="h-10 w-full rounded-lg border border-slate-200 pl-9 pr-3 text-sm" placeholder="Search driver, employee ID or licence"/></label><Select value={status} set={setStatus} options={["ALL","VALID","EXPIRING_SOON","EXPIRED","MISSING","SUSPENDED","RENEWAL_IN_PROGRESS"]}/><Select value={type} set={setType} options={["ALL",...LICENCE_TYPES]}/><Select value={expiry} set={setExpiry} labels={{"7":"Within 7 days","30":"Within 30 days","60":"Within 60 days","90":"Within 90 days"}} options={["ALL","EXPIRED","7","30","60","90"]}/></div><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-xs"><thead className="bg-slate-50"><tr>{["Driver","Employee ID","Licence Number","Licence Type","Licence Category","Issue Date","Expiry Date","Status","Document","Actions"].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{rows.map(l=>{const s=licenceStatus(l,today);return <tr key={l.id} className="border-t"><td className="p-4"><Link className="font-semibold text-blue-600" href={`/dashboard/drivers/${l.driverId}`}>{l.driver.name}</Link>{!l.isCurrent&&<span className="ml-2 text-slate-400">History</span>}</td><td className="p-4">{l.driver.employeeId??"—"}</td><td className="p-4 font-medium"><Link href={`/dashboard/drivers/licences/${l.id}`}>{l.licenceNumber}</Link></td><td className="p-4">{pretty(l.licenceType)}</td><td className="p-4">{l.vehicleClass}</td><td className="p-4">{date(l.issueDate)}</td><td className="p-4">{date(l.expiryDate)}</td><td className="p-4"><span className={`rounded-full px-2 py-1 font-semibold ${licenceStatusClass(s)}`}>{pretty(s)}</span></td><td className="p-4">{l.documents[0]?.fileName??"Missing"}</td><td className="p-4"><Link className="font-semibold text-blue-600" href={`/dashboard/drivers/licences/${l.id}`}>View</Link></td></tr>})}</tbody></table>{!rows.length&&<p className="p-8 text-center text-sm text-slate-500">No matching licences found.</p>}</div></div>
  {open&&<Modal title="Add Licence" close={()=>setOpen(false)}><form onSubmit={submit} className="space-y-5"><div><h3 className="text-sm font-semibold">Driver information</h3><label className={label}>Driver *<select required name="driverId" className={input}><option value="">Select driver</option>{drivers.map(d=><option key={d.id} value={d.id}>{d.name} · {d.employeeId??"No employee ID"} · {d.status}</option>)}</select></label></div><LicenceFields/><label className={label}>Notes<textarea name="notes" className="mt-1 min-h-20 w-full rounded-lg border p-3"/></label>{error&&<p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={saving} className="w-full rounded-lg bg-blue-600 py-2.5 text-sm font-semibold text-white">{saving?"Saving…":"Save licence"}</button></form></Modal>}</div>;
}
export function LicenceFields({licence}:{licence?:Partial<Licence>}) {return <div><h3 className="text-sm font-semibold">Licence information</h3><div className="mt-3 grid gap-4 sm:grid-cols-2"><Field name="licenceNumber" title="Licence number *" value={licence?.licenceNumber}/><label className={label}>Licence type *<select required name="licenceType" defaultValue={licence?.licenceType??""} className={input}><option value="">Select type</option>{LICENCE_TYPES.map(v=><option key={v}>{v}</option>)}</select></label><Field name="vehicleClass" title="Licence category / class *" value={licence?.vehicleClass} placeholder="LMV, HMV"/><Field name="issueDate" title="Issue date *" type="date" value={licence?.issueDate?.slice(0,10)}/><Field name="expiryDate" title="Expiry date *" type="date" value={licence?.expiryDate?.slice(0,10)}/><Field name="renewalDate" title="Renewal date" type="date"/><Field name="issuingAuthority" title="Issuing authority"/><Field name="issuingCountry" title="Issuing country"/><Field name="issuingState" title="Issuing state"/></div></div>}
function Field({name,title,type="text",value,placeholder}:{name:string;title:string;type?:string;value?:string;placeholder?:string}){return <label className={label}>{title}<input required={title.endsWith("*")} name={name} type={type} defaultValue={value} placeholder={placeholder} className={input}/></label>}
function Select({value,set,options,labels={}}:{value:string;set:(v:string)=>void;options:readonly string[];labels?:Record<string,string>}){return <select aria-label="Filter" value={value} onChange={e=>set(e.target.value)} className="h-10 rounded-lg border px-3 text-sm">{options.map(o=><option key={o} value={o}>{labels[o]??pretty(o)}</option>)}</select>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-xl bg-white p-6 shadow-xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-bold">{title}</h2><button aria-label="Close" onClick={close}><X size={20}/></button></div>{children}</div></div>}
