import { CheckCircle2, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { LoginForm } from "@/components/auth/login-form";

export const metadata = { title: "Login | FleetGuard Pro" };

export default function LoginPage() {
  return <main className="grid min-h-screen bg-slate-950 lg:grid-cols-[1.05fr_.95fr]">
    <section className="relative hidden overflow-hidden px-12 py-10 lg:flex lg:flex-col lg:justify-between xl:px-20"><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(37,99,235,.2),transparent_35%)]"/><Link href="/" className="relative flex items-center gap-2.5 font-bold text-white"><span className="grid size-9 place-items-center rounded-lg bg-blue-600"><ShieldCheck size={20}/></span>FleetGuard <span className="text-blue-400">Pro</span></Link><div className="relative max-w-xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-400">Fleet management & vehicle safety</p><h1 className="mt-6 text-5xl leading-[1.06] font-bold tracking-[-.045em] text-white xl:text-6xl">Welcome Back</h1><p className="mt-6 max-w-lg text-lg leading-8 text-slate-400">Access your fleet operations dashboard and manage vehicles, drivers, maintenance and compliance.</p><div className="mt-10 flex flex-wrap gap-x-6 gap-y-3 text-sm text-slate-300">{["Clear fleet visibility","Proactive maintenance","Safer operations"].map(x=><span key={x} className="flex items-center gap-2"><CheckCircle2 size={16} className="text-blue-400"/>{x}</span>)}</div></div><p className="relative text-xs text-slate-600">FleetGuard Pro · Enterprise fleet operations</p></section>
    <section className="flex min-h-screen items-center justify-center bg-slate-50 p-5 sm:p-10"><div className="w-full max-w-md"><Link href="/" className="mb-10 flex items-center gap-2.5 font-bold text-slate-950 lg:hidden"><span className="grid size-9 place-items-center rounded-lg bg-slate-950 text-white"><ShieldCheck size={20}/></span>FleetGuard <span className="text-blue-600">Pro</span></Link><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-[0_12px_40px_-20px_rgba(15,23,42,.18)] sm:p-9"><p className="text-xs font-bold uppercase tracking-[.14em] text-blue-600">Secure account access</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-slate-950">Sign in to FleetGuard Pro</h2><p className="mt-2 text-sm leading-6 text-slate-500">Enter your credentials to access fleet operations.</p><LoginForm/></div><p className="mt-6 text-center text-xs text-slate-400">Protected access for authorized personnel only</p></div></section>
  </main>;
}
