import Link from "next/link";
import { authenticatedUser } from "@/lib/access-control";
import { db } from "@/lib/db";
import { Card } from "@/components/ui/card";
import { DailyActions } from "@/components/inspections/daily-actions";
export const dynamic = "force-dynamic";
export default async function InspectionVehicleDetails() {
  const user = await authenticatedUser(); const start = new Date(); start.setHours(0, 0, 0, 0); const end = new Date(start); end.setDate(end.getDate() + 1);
  const vehicles = await db.vehicle.findMany({ where: { companyId: user.companyId!, status: { notIn: ["SOLD", "DISPOSED"] } }, select: { id: true, vehicleName: true, registrationNumber: true, primaryPhotoUrl: true, status: true, currentKm: true, inspections: { where: { companyId: user.companyId!, inspectionDate: { gte: start, lt: end } }, select: { id: true, status: true, notes: true }, take: 1 } }, orderBy: { vehicleName: "asc" } });
  return <div className="mx-auto max-w-[1200px]"><div className="flex items-end justify-between"><div><p className="text-xs font-medium text-slate-500">Inspection Management</p><h1 className="mt-1 text-2xl font-bold">Vehicle details</h1><p className="mt-1 text-sm text-slate-500">Complete today’s vehicle inspection approval.</p></div><Link href="/dashboard/inspections/history" className="rounded-lg border px-4 py-2 text-xs font-semibold">Vehicle history</Link></div><div className="mt-6 grid gap-5 md:grid-cols-2">{vehicles.map(vehicle => { const inspection = vehicle.inspections[0]; return <Card key={vehicle.id} className="overflow-hidden"><div className="h-36 bg-slate-100">{vehicle.primaryPhotoUrl && <img src={vehicle.primaryPhotoUrl} alt={vehicle.vehicleName} className="h-full w-full object-cover"/>}</div><div className="p-5"><div className="flex justify-between gap-3"><div><h2 className="font-semibold">{vehicle.vehicleName}</h2><p className="mt-1 text-xs text-slate-500">{vehicle.registrationNumber} · {vehicle.currentKm.toLocaleString()} KM</p></div><span className="h-fit rounded-full bg-slate-100 px-2 py-1 text-[10px] font-semibold">{inspection?.status?.replaceAll("_", " ") ?? "PENDING INSPECTION"}</span></div><p className="mt-4 text-xs text-slate-500">Vehicle status: <span className="font-semibold text-slate-700">{vehicle.status.replaceAll("_", " ")}</span></p>{inspection ? <p className="mt-3 text-xs text-emerald-700">Inspection recorded for today.</p> : <div className="mt-4"><DailyActions vehicleId={vehicle.id} name={vehicle.vehicleName} registrationNumber={vehicle.registrationNumber}/></div>}<Link href={`/vehicles/${vehicle.id}`} className="mt-4 inline-block text-xs font-semibold text-blue-600">View vehicle trips →</Link></div></Card>})}</div>{!vehicles.length && <Card className="mt-6 p-10 text-center text-sm text-slate-500">No eligible vehicles found.</Card>}</div>;
}
