"use client";

import { FormEvent, ReactNode, useState } from "react";
import { useRouter } from "next/navigation";
import { LoaderCircle, Plus, RefreshCw, Trash2, Wrench, X } from "lucide-react";

const inputClass="h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm outline-none focus:border-blue-500";

async function jsonRequest(url:string,method:string,body?:Record<string,unknown>){
  const response=await fetch(url,{method,headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});
  const result=await response.json() as{message?:string};
  if(!response.ok)throw new Error(result.message??"Unable to complete this action.");
}

export function ResolveIssueButton({vehicleId,issueId}:{vehicleId:string;issueId:string}){
  const router=useRouter();const[loading,setLoading]=useState(false);
  async function resolve(){const notes=window.prompt("Resolution notes");if(notes===null)return;setLoading(true);try{await jsonRequest(`/api/vehicles/${vehicleId}/issues/${issueId}`,"PATCH",{status:"RESOLVED",resolutionNotes:notes});router.refresh()}catch(error){window.alert(error instanceof Error?error.message:"Unable to resolve issue.")}finally{setLoading(false)}}
  return <button disabled={loading} onClick={resolve} className="rounded-md border px-2.5 py-1.5 text-[11px] font-semibold hover:bg-slate-50">{loading?"Saving…":"Resolve"}</button>;
}

export function DeleteDocumentButton({vehicleId,documentId,name}:{vehicleId:string;documentId:string;name:string}){
  const router=useRouter();const[loading,setLoading]=useState(false);
  async function remove(){if(!window.confirm(`Delete ${name}? This removes its database record.`))return;setLoading(true);try{await jsonRequest(`/api/vehicles/${vehicleId}/documents/${documentId}`,"DELETE");router.refresh()}catch(error){window.alert(error instanceof Error?error.message:"Unable to delete document.")}finally{setLoading(false)}}
  return <button disabled={loading} onClick={remove} title="Delete document" className="rounded-md p-2 text-red-600 hover:bg-red-50"><Trash2 size={14}/></button>;
}

export function EditDocumentButton({vehicleId,document,replace=false}:{vehicleId:string;document:{id:string;documentName:string|null;documentNumber:string|null;issueDate:string|null;expiryDate:string|null;notes:string|null;fileName:string};replace?:boolean}){
  const router=useRouter();const[open,setOpen]=useState(false);const[loading,setLoading]=useState(false);const[error,setError]=useState("");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError("");const form=new FormData(event.currentTarget);const body:Record<string,unknown>={documentName:String(form.get("documentName")||""),documentNumber:String(form.get("documentNumber")||"")||null,issueDate:String(form.get("issueDate")||"")||null,expiryDate:String(form.get("expiryDate")||"")||null,notes:String(form.get("notes")||"")||null};if(replace){body.fileUrl=String(form.get("fileUrl")||"");body.fileName=String(form.get("fileName")||"")}try{await jsonRequest(`/api/vehicles/${vehicleId}/documents/${document.id}`,"PATCH",body);setOpen(false);router.refresh()}catch(error){setError(error instanceof Error?error.message:"Unable to update document.")}finally{setLoading(false)}}
  return <><button onClick={()=>setOpen(true)} className="rounded-md border px-2 py-1.5 text-[11px] font-semibold hover:bg-slate-50">{replace?"Replace":"Edit"}</button>{open&&<Modal title={`${replace?"Replace":"Edit"} document`} onClose={()=>setOpen(false)}><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><Field name="documentName" label="Document name" required defaultValue={document.documentName??""}/><Field name="documentNumber" label="Document number" defaultValue={document.documentNumber??""}/><Field name="issueDate" label="Issue date" type="date" defaultValue={document.issueDate?.slice(0,10)??""}/><Field name="expiryDate" label="Expiry date" type="date" defaultValue={document.expiryDate?.slice(0,10)??""}/>{replace&&<><Field name="fileName" label="Replacement file name" required defaultValue={document.fileName}/><Field name="fileUrl" label="Replacement storage URL" required/></>}<div className="sm:col-span-2"><Field name="notes" label="Notes" defaultValue={document.notes??""}/></div>{error&&<p className="sm:col-span-2 text-sm text-red-600">{error}</p>}<div className="sm:col-span-2"><SubmitRow loading={loading} onCancel={()=>setOpen(false)}/></div></form></Modal>}</>;
}

export function EditServiceButton({vehicleId,service}:{vehicleId:string;service:{id:string;provider:string|null;notes:string|null;nextServiceDate:string|null;nextServiceKm:number|null}}){
  const router=useRouter();const[open,setOpen]=useState(false);const[loading,setLoading]=useState(false);const[error,setError]=useState("");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError("");const form=new FormData(event.currentTarget);try{await jsonRequest(`/api/vehicles/${vehicleId}/services/${service.id}`,"PATCH",{provider:form.get("provider")||null,notes:form.get("notes")||null,nextServiceDate:form.get("nextServiceDate")||null,nextServiceKm:form.get("nextServiceKm")?Number(form.get("nextServiceKm")):null});setOpen(false);router.refresh()}catch(error){setError(error instanceof Error?error.message:"Unable to update service.")}finally{setLoading(false)}}
  return <><button onClick={()=>setOpen(true)} className="rounded-md border px-2.5 py-1.5 text-[11px] font-semibold hover:bg-slate-50">Edit</button>{open&&<Modal title="Edit service record" onClose={()=>setOpen(false)}><form onSubmit={submit} className="space-y-4"><Field name="provider" label="Provider" defaultValue={service.provider??""}/><Field name="nextServiceDate" label="Next service date" type="date" defaultValue={service.nextServiceDate?.slice(0,10)??""}/><Field name="nextServiceKm" label="Next service KM" type="number" defaultValue={service.nextServiceKm??""}/><Field name="notes" label="Notes" defaultValue={service.notes??""}/>{error&&<p className="text-sm text-red-600">{error}</p>}<SubmitRow loading={loading} onCancel={()=>setOpen(false)}/></form></Modal>}</>;
}

type Tyre={id:string;position:string;brand:string;model:string|null;size:string|null;serialNumber:string|null;installationDate:string;installationKm:number|null;pressure:number|null;condition:string;status:string;cost:number|null};
export function TyreActions({vehicleId,currentKm,tyres}:{vehicleId:string;currentKm:number;tyres:Tyre[]}){
  const router=useRouter();const[mode,setMode]=useState<"add"|"edit"|"replace">();const[selected,setSelected]=useState<Tyre>();const[loading,setLoading]=useState(false);const[error,setError]=useState("");
  function showEdit(tyre:Tyre){setSelected(tyre);setMode("edit");setError("")}
  function showReplace(tyre:Tyre){setSelected(tyre);setMode("replace");setError("")}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError("");const form=new FormData(event.currentTarget);const common={brand:String(form.get("brand")||""),model:String(form.get("model")||"")||null,size:String(form.get("size")||"")||null,serialNumber:String(form.get("serialNumber")||"")||null,cost:form.get("cost")?Number(form.get("cost")):null};try{if(mode==="add")await jsonRequest(`/api/vehicles/${vehicleId}/tyres`,"POST",{...common,position:String(form.get("position")||""),installationDate:String(form.get("date")||""),installationKm:Number(form.get("km")),pressure:form.get("pressure")?Number(form.get("pressure")):undefined,condition:"New",status:"GOOD"});else if(mode==="edit"&&selected)await jsonRequest(`/api/vehicles/${vehicleId}/tyres/${selected.id}`,"PATCH",{...common,position:String(form.get("position")||""),installationDate:String(form.get("date")||""),installationKm:Number(form.get("km")),pressure:form.get("pressure")?Number(form.get("pressure")):null,condition:String(form.get("condition")||"Good"),status:String(form.get("status")||"GOOD")});else if(selected)await jsonRequest(`/api/vehicles/${vehicleId}/tyres/${selected.id}/replace`,"POST",{...common,replacementDate:String(form.get("date")||""),replacementKm:Number(form.get("km"))});setMode(undefined);router.refresh()}catch(error){setError(error instanceof Error?error.message:"Unable to save tyre.")}finally{setLoading(false)}}
  return <><div className="mb-4 flex justify-end"><button onClick={()=>{setSelected(undefined);setMode("add");setError("")}} className="flex items-center gap-2 rounded-lg bg-blue-600 px-3 py-2 text-xs font-semibold text-white"><Plus size={14}/>Add tyre</button></div>{tyres.length>0&&<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{tyres.filter(t=>t.status!=="REPLACED").map(tyre=><div key={tyre.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between"><strong className="text-sm">{tyre.position}</strong><span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-semibold text-emerald-700">{tyre.status.replaceAll("_"," ")}</span></div><p className="mt-3 text-xs text-slate-600">{tyre.brand} {tyre.model}</p><p className="mt-1 text-xs text-slate-400">{tyre.size||"Size not recorded"}</p><div className="mt-4 flex gap-3"><button onClick={()=>showEdit(tyre)} className="text-[11px] font-semibold text-blue-600">Edit</button><button onClick={()=>showReplace(tyre)} className="flex items-center gap-1 text-[11px] font-semibold text-blue-600"><RefreshCw size={12}/>Replace</button></div></div>)}</div>}{mode&&<Modal title={mode==="add"?"Add tyre":mode==="edit"?`Edit ${selected?.position} tyre`:`Replace ${selected?.position} tyre`} onClose={()=>setMode(undefined)}><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2">{mode!=="replace"&&<Field name="position" label="Position" required defaultValue={selected?.position}/>}<Field name="brand" label="Brand" required defaultValue={selected?.brand}/><Field name="model" label="Model" defaultValue={selected?.model??""}/><Field name="size" label="Size" defaultValue={selected?.size??""}/><Field name="serialNumber" label="Serial number" defaultValue={mode==="edit"?selected?.serialNumber??"":""}/><Field name="date" label={mode==="replace"?"Replacement date":"Installation date"} type="date" required defaultValue={mode==="edit"?selected?.installationDate.slice(0,10):undefined}/><Field name="km" label={mode==="replace"?"Replacement KM":"Installation KM"} type="number" defaultValue={mode==="edit"?selected?.installationKm??currentKm:currentKm} required/>{mode!=="replace"&&<Field name="pressure" label="Pressure" type="number" defaultValue={selected?.pressure??""}/>} {mode==="edit"&&<><Field name="condition" label="Tread condition" defaultValue={selected?.condition}/><label className="block text-xs font-medium text-slate-700">Status<select name="status" defaultValue={selected?.status} className={`${inputClass} mt-1.5`}>{["GOOD","MONITOR","INSPECTION_REQUIRED","REPLACE_SOON","REPLACE_IMMEDIATELY"].map(status=><option key={status}>{status}</option>)}</select></label></>}<Field name="cost" label="Cost" type="number" defaultValue={selected?.cost??""}/>{error&&<p className="sm:col-span-2 text-sm text-red-600">{error}</p>}<div className="sm:col-span-2"><SubmitRow loading={loading} onCancel={()=>setMode(undefined)}/></div></form></Modal>}</>;
}

function Field({name,label,type="text",required,defaultValue}:{name:string;label:string;type?:string;required?:boolean;defaultValue?:string|number}){return <label className="block text-xs font-medium text-slate-700">{label}{required&&" *"}<input name={name} type={type} required={required} min={type==="number"?0:undefined} step={type==="number"?"any":undefined} defaultValue={defaultValue} className={`${inputClass} mt-1.5`}/></label>}
function SubmitRow({loading,onCancel}:{loading:boolean;onCancel:()=>void}){return <div className="flex justify-end gap-2"><button type="button" onClick={onCancel} className="rounded-lg border px-4 py-2 text-sm font-semibold">Cancel</button><button disabled={loading} className="flex items-center rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white">{loading&&<LoaderCircle size={15} className="mr-2 animate-spin"/>}{loading?"Saving…":"Save"}</button></div>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <div className="fixed inset-0 z-[95] grid place-items-center bg-slate-950/50 p-4" onMouseDown={onClose}><div role="dialog" aria-modal="true" className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-xl bg-white p-6 shadow-xl" onMouseDown={e=>e.stopPropagation()}><div className="mb-5 flex items-center justify-between"><h2 className="flex items-center gap-2 text-lg font-semibold"><Wrench size={18}/>{title}</h2><button onClick={onClose} aria-label="Close"><X size={19}/></button></div>{children}</div></div>}
