import { AlertTriangle, ArrowRight, Check, FileWarning, Fuel, MapPinOff, ShieldCheck, Wrench, X } from "lucide-react";
import { Reveal } from "@/components/motion/reveal";
import { Button } from "@/components/ui/button";
import { features, industries, solutions } from "@/lib/constants";

export function TrustSection() {
  return <section className="border-y border-slate-200 bg-white py-10"><div className="container-page"><p className="text-center text-sm font-medium text-slate-500">Built for organizations managing multiple vehicles</p><div className="mt-7 grid grid-cols-2 gap-5 sm:grid-cols-3 lg:grid-cols-5">{industries.map(({name,icon:Icon})=><div key={name} className="flex items-center justify-center gap-2 text-sm font-semibold text-slate-500"><Icon size={18} className="text-slate-400"/>{name}</div>)}</div></div></section>;
}

const problems = [["Missed service schedules",Wrench],["Expired insurance",FileWarning],["Poor vehicle visibility",MapPinOff],["Uncontrolled fuel expenses",Fuel],["Vehicle damage disputes",AlertTriangle],["Manual, fragmented records",X]] as const;

export function ProblemSection() {
  return <section className="section-pad bg-slate-950 text-white"><div className="container-page grid gap-14 lg:grid-cols-[.8fr_1.2fr] lg:gap-24"><Reveal><p className="eyebrow text-blue-400">The operational gap</p><h2 className="section-title text-white">Your fleet is too important to run on reminders and spreadsheets.</h2><p className="section-copy text-slate-400">When vehicle data lives in different places, deadlines are missed, costs become invisible and accountability gets harder.</p></Reveal><div className="grid gap-3 sm:grid-cols-2">{problems.map(([title,Icon],i)=><Reveal key={title} delay={i*.04}><div className="flex h-full items-center gap-4 rounded-xl border border-slate-800 bg-slate-900/70 p-5"><span className="grid size-10 shrink-0 place-items-center rounded-lg bg-red-500/10 text-red-400"><Icon size={19}/></span><p className="text-sm font-medium text-slate-200">{title}</p></div></Reveal>)}</div></div></section>;
}

export function SolutionsSection() {
  return <section id="solutions" className="section-pad bg-white"><div className="container-page"><Reveal><p className="eyebrow">One connected platform</p><h2 className="section-title">Make every fleet decision from complete, current information.</h2><p className="section-copy">FleetGuard Pro brings vehicles, people, maintenance and compliance into a single operating system designed for daily work.</p></Reveal><div className="mt-14 grid gap-px overflow-hidden rounded-2xl border border-slate-200 bg-slate-200 md:grid-cols-2 lg:grid-cols-3">{solutions.map(({title,text,icon:Icon},i)=><Reveal key={title} delay={i*.04} className="bg-white"><article className="group h-full p-7 transition hover:bg-slate-50"><span className="grid size-11 place-items-center rounded-lg border border-slate-200 bg-white text-blue-600 shadow-sm"><Icon size={21}/></span><h3 className="mt-6 text-lg font-semibold tracking-tight">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p></article></Reveal>)}</div></div></section>;
}

export function FeaturesSection() {
  return <section id="features" className="section-pad bg-[#f7f9fc]"><div className="container-page"><Reveal className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="eyebrow">Built for the work</p><h2 className="section-title">Everything your team needs to operate with confidence.</h2></div><p className="max-w-md text-base leading-7 text-slate-600">A practical toolkit that helps your operation stay safe, compliant and cost-aware—without adding complexity.</p></Reveal><div className="mt-14 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{features.map(([title,text,Icon],i)=><Reveal key={title} delay={(i%5)*.035}><article className="h-full rounded-xl border border-slate-200 bg-white p-5 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-md"><Icon size={20} className="text-blue-600"/><h3 className="mt-5 text-sm font-semibold">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{text}</p></article></Reveal>)}</div></div></section>;
}

const steps = ["Register vehicles","Assign drivers","Inspect before use","Track maintenance","Receive alerts","Improve fleet safety"];
export function WorkflowSection() {
  return <section id="how-it-works" className="section-pad bg-white"><div className="container-page"><Reveal className="text-center"><p className="eyebrow">How it works</p><h2 className="section-title mx-auto">A safer fleet starts with a clear process.</h2><p className="section-copy mx-auto">Set up once, then give your team a consistent operating rhythm.</p></Reveal><div className="relative mt-16 grid gap-4 md:grid-cols-3 lg:grid-cols-6"><div className="absolute top-6 right-[8%] left-[8%] hidden h-px bg-slate-200 lg:block"/>{steps.map((step,i)=><Reveal key={step} delay={i*.05} className="relative"><div className="flex items-center gap-4 rounded-xl border border-slate-200 bg-white p-4 lg:block lg:border-0 lg:p-0 lg:text-center"><span className="relative z-10 grid size-12 shrink-0 place-items-center rounded-full border-4 border-white bg-slate-950 text-sm font-bold text-white shadow-sm">{i+1}</span><p className="text-sm font-semibold lg:mt-5">{step}</p></div></Reveal>)}</div></div></section>;
}

export function DashboardSection() {
  const rows = [["MH 12 RT 4821","Tata Ultra","On trip","Pune → Mumbai","Healthy"],["MH 14 JL 9028","Mahindra Bolero","Available","Pune depot","Service due"],["GJ 01 KU 1104","Ashok Leyland","On trip","Surat → Nashik","Healthy"],["MH 02 NX 7710","Toyota Innova","Inactive","Mumbai office","Document due"]];
  return <section className="section-pad overflow-hidden bg-[#f7f9fc]"><div className="container-page"><Reveal className="text-center"><p className="eyebrow">Operational clarity</p><h2 className="section-title mx-auto">Your entire fleet. One dependable view.</h2><p className="section-copy mx-auto">See vehicle status, driver activity, service priorities and compliance risks without chasing updates.</p></Reveal><Reveal className="mt-14"><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_24px_70px_-35px_rgba(15,23,42,.35)]"><div className="flex flex-col gap-4 border-b border-slate-200 px-6 py-5 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-semibold">Fleet overview</h3><p className="mt-1 text-xs text-slate-500">128 vehicles across 4 locations</p></div><div className="flex gap-2"><span className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-medium">All locations</span><span className="rounded-lg bg-blue-600 px-3 py-2 text-xs font-medium text-white">+ Add vehicle</span></div></div><div className="grid gap-px bg-slate-200 sm:grid-cols-3"><Metric label="Fleet availability" value="84%" note="108 vehicles ready"/><Metric label="Maintenance compliance" value="96.2%" note="+2.4% this month"/><Metric label="Monthly distance" value="184,920 km" note="Across all vehicles"/></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead className="bg-slate-50 text-[11px] uppercase tracking-wider text-slate-500"><tr>{["Vehicle","Model","Status","Current location","Maintenance"].map(x=><th key={x} className="px-6 py-4 font-semibold">{x}</th>)}</tr></thead><tbody>{rows.map((r)=><tr key={r[0]} className="border-t border-slate-100 text-sm"><td className="px-6 py-4 font-semibold">{r[0]}</td><td className="px-6 py-4 text-slate-600">{r[1]}</td><td className="px-6 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${r[2]==="On trip"?"bg-blue-50 text-blue-700":r[2]==="Available"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{r[2]}</span></td><td className="px-6 py-4 text-slate-600">{r[3]}</td><td className={`px-6 py-4 text-xs font-medium ${r[4]==="Healthy"?"text-emerald-700":"text-amber-700"}`}>{r[4]}</td></tr>)}</tbody></table></div></div></Reveal></div></section>;
}
function Metric({label,value,note}:{label:string;value:string;note:string}) { return <div className="bg-white p-6"><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold tracking-tight">{value}</p><p className="mt-1 text-xs text-slate-500">{note}</p></div> }

export function SecuritySection() {
  const points=["Role-based access for every team","Secure document storage","Complete activity tracking","Enterprise-grade data protection"];
  return <section id="security" className="section-pad bg-white"><div className="container-page grid items-center gap-14 lg:grid-cols-2 lg:gap-24"><Reveal><div className="relative mx-auto grid aspect-square max-w-[430px] place-items-center rounded-full border border-slate-200 bg-slate-50"><div className="absolute inset-[14%] rounded-full border border-dashed border-blue-300"/><div className="grid size-32 place-items-center rounded-3xl bg-slate-950 text-white shadow-2xl"><ShieldCheck size={56}/></div><span className="absolute top-[12%] right-[18%] rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-semibold shadow-sm">Encrypted</span><span className="absolute bottom-[16%] left-[10%] rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-semibold shadow-sm">Access controlled</span></div></Reveal><Reveal><p className="eyebrow">Security by design</p><h2 className="section-title">Your operational data stays protected and accountable.</h2><p className="section-copy">FleetGuard Pro is structured around the people who use it, giving every role appropriate access while preserving a reliable record of activity.</p><div className="mt-8 space-y-4">{points.map(p=><div key={p} className="flex items-center gap-3 text-sm font-medium"><span className="grid size-6 place-items-center rounded-full bg-blue-50 text-blue-600"><Check size={14}/></span>{p}</div>)}</div></Reveal></div></section>;
}

export function CtaSection() { return <section id="contact" className="bg-white pb-10"><div className="container-page"><Reveal><div className="overflow-hidden rounded-3xl bg-slate-950 px-6 py-16 text-center text-white sm:px-12 sm:py-20"><p className="eyebrow text-blue-400">Move your fleet forward</p><h2 className="mx-auto mt-5 max-w-2xl text-4xl font-bold tracking-[-.04em] sm:text-5xl">Take control of your fleet operations</h2><p className="mx-auto mt-5 max-w-xl leading-7 text-slate-400">See how FleetGuard Pro can bring clarity, safety and control to your daily operation.</p><a href="mailto:hello@fleetguardpro.com?subject=FleetGuard%20Pro%20Demo"><Button variant="light" className="mt-8 gap-2">Request Demo <ArrowRight size={16}/></Button></a></div></Reveal></div></section> }
