ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'INSPECTOR';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'MAINTENANCE_STAFF';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'FINANCE';

ALTER TABLE "users"
  ADD COLUMN IF NOT EXISTS "active" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "last_login_at" TIMESTAMP(3);
