import Link from "next/link";
import { Plus } from "lucide-react";
import { Card } from "@/components/ui/card";
import { authenticatedUser } from "@/lib/access-control";
import { db } from "@/lib/db";
import { RegistrationActions } from "@/components/vehicles/registration-actions";

export default async function Registration({ searchParams }: { searchParams: Promise<{ includeInactive?: string }> }) {
  const query = await searchParams;
  const user = await authenticatedUser();
  const vehicles = await db.vehicle.findMany({
    where: { companyId: user.companyId!, ...(query.includeInactive === "1" ? {} : { status: { not: "INACTIVE" } }) },
    select: { id: true, vehicleName: true, vehicleCode: true, registrationNumber: true, registrationDate: true, rcNumber: true, ownerName: true, registrationAuthority: true, status: true },
    orderBy: { registrationNumber: "asc" },
  });
  return <div className="mx-auto max-w-[1500px]"><div className="mb-6 flex items-end justify-between gap-4"><div><h1 className="text-2xl font-bold">Vehicle registration</h1><p className="mt-1 text-sm text-slate-500">Manage registration records connected to your fleet.</p></div><Link href="/vehicles/new" className="flex h-10 items-center gap-2 rounded-lg bg-blue-600 px-4 text-sm font-semibold text-white"><Plus size={16}/>Register vehicle</Link></div><Card className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-xs"><thead className="bg-slate-50"><tr>{["Vehicle", "Registration number", "Registration date", "RC number", "Owner", "Registration authority", "Status", "Actions"].map(x => <th className="whitespace-nowrap px-4 py-3 font-semibold text-slate-600" key={x}>{x}</th>)}</tr></thead><tbody>{vehicles.map(vehicle => <tr className="border-t border-slate-100" key={vehicle.id}><td className="px-4 py-4"><Link href={`/vehicles/${vehicle.id}`} className="font-semibold text-blue-600">{vehicle.vehicleName}</Link><span className="mt-1 block text-[10px] text-slate-400">{vehicle.vehicleCode}</span></td><td className="px-4 py-4 font-medium">{vehicle.registrationNumber}</td><td className="px-4 py-4">{vehicle.registrationDate?.toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" }) ?? "—"}</td><td className="px-4 py-4">{vehicle.rcNumber ?? "—"}</td><td className="px-4 py-4">{vehicle.ownerName ?? "—"}</td><td className="px-4 py-4">{vehicle.registrationAuthority ?? "—"}</td><td className="px-4 py-4"><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${vehicle.status === "INACTIVE" ? "bg-slate-100 text-slate-600" : "bg-emerald-50 text-emerald-700"}`}>{vehicle.status === "INACTIVE" ? "INACTIVE" : "ACTIVE"}</span></td><td className="px-4 py-4"><RegistrationActions vehicle={{ id: vehicle.id, vehicleName: vehicle.vehicleName, registrationNumber: vehicle.registrationNumber, status: vehicle.status }} /></td></tr>)}</tbody></table>{!vehicles.length && <p className="p-10 text-center text-sm text-slate-500">No active vehicle registration records found.</p>}<div className="flex items-center justify-between border-t border-slate-200 px-4 py-3 text-xs text-slate-500"><span>Showing {vehicles.length} registration records</span><Link href={query.includeInactive === "1" ? "/vehicles/registration" : "/vehicles/registration?includeInactive=1"} className="font-semibold text-blue-600">{query.includeInactive === "1" ? "Hide deactivated" : "Show deactivated"}</Link></div></Card></div>;
}
