import Link from "next/link";
import { Card } from "@/components/ui/card";
import { authenticatedUser } from "@/lib/access-control";
import { db } from "@/lib/db";

export const dynamic = "force-dynamic";
export default async function TyreInventoryPage() {
  const user = await authenticatedUser();
  const tyres = await db.tyre.findMany({ where: { vehicle: { companyId: user.companyId! } }, include: { vehicle: { select: { id: true, vehicleName: true, registrationNumber: true, currentKm: true } } }, orderBy: { createdAt: "desc" } });
  const fitted = tyres.filter(t => t.status !== "REPLACED").length;
  return <div className="mx-auto max-w-[1400px]"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-medium text-slate-500">Tyre & Wheel Management</p><h1 className="mt-1 text-2xl font-bold">Tyre inventory</h1><p className="mt-1 text-sm text-slate-500">Track fitted tyres, condition, position, and lifecycle history.</p></div><div className="flex gap-2"><Link href="/dashboard/tyres/inspection" className="rounded-lg border px-4 py-2 text-xs font-semibold">Tyre inspection</Link><Link href="/dashboard/tyres/history" className="rounded-lg border px-4 py-2 text-xs font-semibold">Tyre history</Link></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Total tyres" value={tyres.length}/><Metric label="Fitted / active" value={fitted}/><Metric label="Needs inspection" value={tyres.filter(t => t.status === "INSPECTION_REQUIRED").length}/><Metric label="Replace soon" value={tyres.filter(t => ["REPLACE_SOON","REPLACE_IMMEDIATELY"].includes(t.status)).length}/></div><Card className="mt-6 overflow-x-auto"><table className="w-full text-left"><thead className="bg-slate-50"><tr>{["Tyre ID","Vehicle","Position","Brand / model","Size","Serial number","Installed","Pressure","Condition","Status"].map(x=><th key={x} className="whitespace-nowrap px-4 py-3 text-xs font-semibold text-slate-600">{x}</th>)}</tr></thead><tbody>{tyres.map(tyre=><tr key={tyre.id} className="border-t text-xs"><td className="px-4 py-4 font-semibold">{tyre.id.slice(-8).toUpperCase()}</td><td className="px-4 py-4"><Link href={`/vehicles/${tyre.vehicle.id}?tab=Tyres`} className="font-semibold text-blue-600">{tyre.vehicle.vehicleName}</Link><br/>{tyre.vehicle.registrationNumber}</td><td className="px-4 py-4">{tyre.position}</td><td className="px-4 py-4">{tyre.brand} {tyre.model ?? ""}</td><td className="px-4 py-4">{tyre.size ?? "—"}</td><td className="px-4 py-4">{tyre.serialNumber ?? "—"}</td><td className="px-4 py-4">{tyre.installationKm?.toLocaleString() ?? "—"} KM</td><td className="px-4 py-4">{tyre.pressure?.toString() ?? "—"}</td><td className="px-4 py-4">{tyre.condition}</td><td className="px-4 py-4">{tyre.status.replaceAll("_", " ")}</td></tr>)}</tbody></table>{!tyres.length&&<p className="p-10 text-center text-sm text-slate-500">No tyres recorded yet. Add tyres from a vehicle’s Tyres tab.</p>}</Card></div>;
}
function Metric({ label, value }: { label: string; value: number }) { return <Card className="p-5"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></Card>; }
